# client/pnpm-workspace.yaml
packages:
  - "."

minimumReleaseAge: 2880
trustPolicy: no-downgrade
blockExoticSubdeps: true

overrides:
  semver: ">=7.7.3"

allowBuilds:
  "@swc/core": true
  esbuild: true
